sonar.organization=havo-ao_eco-ride-api
sonar.projectKey=havo-ao
sonar.projectName=EcoRide Backend
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,**/*.spec.ts,**/*.test.ts
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.d.ts,**/dtos/**,**/config/**,**/database/**,**/app.ts,**/server.ts
